### ISSUE TITLE
Highlight selected elements 

### ISSUE THREAD

**Issue by ShehabFekry** [xBimTeam/XbimEssentials#516] opened 2023-08-12 17:34 UTC
*Short summary describing the issue. (3-5 sentences)*
I have created a desktop application that compares the changes between two IFC files 
now I want to open the IFC windows viewer from that desktop application and press a button to highlight some global Ids that I already have.

#### Assemblies and versions affected:

Xbim.Essentials 4.0.29__*

#### Steps (or code) to reproduce the issue:

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

```csharp

                using (var modelTwo = IfcStore.Open(FilePathOld))
                {

                    var element= modelTwo.Instances.OfType<IIfcElement>().First();
                   var id = element.GlobalId;




#### Expected behavior:

*What would you expect to happen*

I have a desktop application with some Ids that i've stored .. I want to have two buttons 
one button opening the xbim Xplorer in windows and loads the latest IFC file on it 

the second button highlights the elements with ids from the list that i will pass.

**Comment by andyward** [comment] 2023-08-14 08:55
Duplicate of https://github.com/xBimTeam/XbimWindowsUI/issues/208

**Closed by andyward** 2023-08-14 08:55 UTC
