### ISSUE TITLE
IFC files throwing exception in Xbim.IO.dll

### ISSUE THREAD

**Issue by daveime** [xBimTeam/XbimEssentials#127] opened 2018-01-12 05:35 UTC
I'm using Xbim.Essentials.4.0.29-V006 and the three linked files are all throwing the following exception during inital parsing

Exception thrown: 'Xbim.Common.Exceptions.XbimParserException' in Xbim.IO.dll ("Parser failed on line 0, column 0").

http://marikinacgi.com/IFC/FILE1.zip
http://marikinacgi.com/IFC/FILE2.zip
http://marikinacgi.com/IFC/FILE3.zip

These were all created using "The EXPRESS Data Manager Version 5.02.0100.07 : 28 Aug 2013", however I do have other files created with the same system that do parse and load correctly.

Do you think you could take a look and comment on any patches etc that may have already resolved these issues, and how I might obtain / build either thru NuGet or source build.

Dave

**Comment by martin1cerny** [comment] 2018-01-12 09:00
I had a look and the problem is that these files are not IFC4 schema compliant. There are many instances of `IfcRelConnectsPortToElement` which reference general `IfcBuildingElementProxy` but can only reference `IfcDistributionElement`. That is [a change in IFC4](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcrelconnectsporttoelement.htm).. I realized recently that default IFC exporter which comes with Revit 2018 doesn't handle type mapping correctly for many types and uses `IfcBuildingElementProxy` as a fallback. This is fixed in the latest version of exporter [(separate download)](https://sourceforge.net/projects/ifcexporter/). That is why some files are OK. They either don't contain `IfcRelConnectsPortToElement` or they use newer version of exporter (they will be using the same version of EXPRESS Data Manager). This is also in the header.

When xBIM parser finds too many errors in the file it fails completely which is the general exception you noticed. If you [set up a logger](http://docs.xbim.net/examples/watch-the-log.html) you would see these errors. Also, inner exception of the exception you caught provides more detail on what happened.

This specific kind of error could be fixed automatically by changing the `IfcBuildingElementProxy` type of object to `IfcDistributionElement` because they are binary compatible but xBIM doesn't do this at the moment.

First few erroneous lines from your FILE1.ifc
```
Entity #201032 IFCRELCONNECTSPORTTOELEMENT, error at parameter 6-RelatedElement value = #385=IFCBUILDINGELEMENTPROXY
Entity #201043 IFCRELCONNECTSPORTTOELEMENT, error at parameter 6-RelatedElement value = #385=IFCBUILDINGELEMENTPROXY
Entity #201065 IFCRELCONNECTSPORTTOELEMENT, error at parameter 6-RelatedElement value = #432=IFCBUILDINGELEMENTPROXY
Entity #201096 IFCRELCONNECTSPORTTOELEMENT, error at parameter 6-RelatedElement value = #432=IFCBUILDINGELEMENTPROXY
...
Number of errors: 60
```

While I was exploring this I have improved the log and error handling so you are better to get the latest `develop` build/source. Every such an error was counted 3 times which didn't help. But the essential problem is in the data which breaks the schema. As a result these relations will not be populated by the right data and the resulting model is incomplete.

**Comment by daveime** [comment] 2018-01-15 02:30
Martin,

Thank you for this comprehensive response. You stated

"This specific kind of error could be fixed automatically by changing the IfcBuildingElementProxy type of object to IfcDistributionElement because they are binary compatible but xBIM doesn't do this at the moment."

Is this on your bucket list for the future? I understand hacking the XBim parser to handle essentially "bad files" might go against your principles, but by the same token I'm a bit loathe on my end to swap out the built-in IFC exporter in Revit 2014-2018 with the custom open-source ones, as I worry that might introduce another swathe of issues.

I'm going to have a look at the XBim latest dev source and see if I can code my own hack for this. If it works out, I'll submit it to you.

Thanks
Dave

**Comment by daveime** [comment] 2018-01-15 04:28
Martin,

Apologies for re-opening the issue.

I can see during debugging IfcRelConnectsPortToElement.cs, that the cast is failing in line 122.

_relatedElement = (IfcDistributionElement)(value.EntityVal);

EntityVal is already created as a BuildingElementProxy and indexed by the Model in various lists etc.

Does there exist a function in the codebase to "reparse" an element as a specific type and replace the existing one? Because obviously, until we add a try-catch block to see if this cast fails, we don't know that this BuildingElementProxy needs to be converted into a DistributionElement.

**Comment by martin1cerny** [comment] 2018-01-15 07:54
As I said, it is not implemented in xBIM right now and it is not trivial. There is a place in the parser where we could check if the type is compatible in the catch statement where parser errors are handled. But reparsing is a non-existing concept right now. It would mean to remove the entity completely and to replace all references to it in the model. While this is doable it is a non-trivial task and it would only allow automated handlig of very few types of errors. This case is very specific because `IfcDistributionElement` is not an abstract class which is not the case for most of similar relations. The most straightforward way I can see now is some kind of text pre-processing with regular expressions to find these very specific cases and replace them in the file before the parsing starts. You can use the code in MemoryModel to only read the header to see if it is the eroneous Revit exporter version (IFC4 && Exporter < 18.2).

**Comment by martin1cerny** [comment] 2018-01-15 07:58
A note on Revit Exporter: The built-in exporter **IS** the open source one. It is just not the latest version. While Revit lives in 1 year release cycles there are usualy several releases of the exporter in the meantime. This allows for more agile development of the exporter and we can confirm that it has very posivite general impact on the development and increasing quality of the data exported.

**Comment by daveime** [comment] 2018-01-19 06:18
Martin,

Thank you for your patience. I understand now entirely why there's no "reparse" as such.

Your insights on the open-source exporters are welcome, I may have no other choice but to look at them now. As we're trying to support Revit 2015-2018, do you happen to know if those open-source replacements apply these fixes retroactively? I mean if they're using BuildingElementProxy when they should be using DistributionElement, does this patch get applied to all previous versions or just the current 2018 one they detected it on?

Thanks
Dave

**Comment by martin1cerny** [comment] 2018-01-19 08:51
Looking at their [releases](https://sourceforge.net/projects/ifcexporter/files/) it seems they do support previous versions to some extent but you will need to check this yourself. If you do such a test of functionality I'd appreciate it a lot if you could share your findings (public or private). IFC4 DTV option in exporter is great as it is faster and creates smaller files but loosing type information is a shame and creates non-compliant data sets in some cases. I'm actually quite surprised they don't use early binding and schema validation for their outputs because xBIM for example wouldn't even be able to create such a mess.

Best regards

Martin

**Closed** 2018-02-14 13:12 UTC
