### ISSUE TITLE
Not rendering correct wexBIM after conversion

### ISSUE THREAD

**Issue by ivanstef** [xBimTeam/XbimEssentials#43] opened 2016-06-28 11:50 UTC
Hi, guys I have some great issues with the latest version of the myget packages. The rendering of the wexBIM file after the conversion is getting worse. I am attaching a screenshot. In my last issue I posted the file that I am playing with. In one of the previous versions it was working great.

**Comment by ivanstef** [comment] 2016-06-28 11:53
[
![28-06-2016-1467113062793](https://cloud.githubusercontent.com/assets/5886640/16414397/1021d39a-3d40-11e6-97dc-1e08c020efe9.png)
](url)

**Comment by martin1cerny** [comment] 2016-09-23 21:02
Duplicate of issue #29

**Closed by martin1cerny** 2016-09-23 21:02 UTC
