### ISSUE TITLE
Unable to convert ifc to wexbim.

### ISSUE THREAD

**Issue by fouziyapatel** [xBimTeam/XbimEssentials#85] opened 2017-05-17 07:42 UTC
Hello ,
     I'm facing an exception while converting  IFC file to wexbim . Just before creating context it gives this exception .I have attached the file .Please let me know the solution asap.
Thanks.

`[InvalidOperationException: Stack empty.]
   System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) +60
   System.Collections.Generic.Stack`1.Pop() +8479810
   Xbim.IO.Step21.XbimP21Parser.EndEntity() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:206
   QUT.Gppg.ShiftReduceParser`2.Reduce(Int32 ruleNumber) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:332
   QUT.Gppg.ShiftReduceParser`2.Parse() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:263
   Xbim.IO.Memory.MemoryModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:536
   Xbim.IO.Memory.MemoryModel.LoadStep21(String file, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:550
   Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.Ifc\IfcStore.cs:362
   WebApplication_XBIM_3D._Default.ConvertIfcToWexBIM() in d:\Fouziya\Server\WebApplication_XBIM 3D\WebApplication_XBIM 3D\Default.aspx.cs:27
   WebApplication_XBIM_3D._Default.Page_Load(Object sender, EventArgs e) in d:\Fouziya\Server\WebApplication_XBIM 3D\WebApplication_XBIM 3D\Default.aspx.cs:17
   System.Web.UI.Control.OnLoad(EventArgs e) +109
   System.Web.UI.Control.LoadRecursive() +68
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4498`

**Comment by martin1cerny** [comment] 2017-05-17 09:14
Using Xbim.Essentials 4.0.28-V018 I was able to open the file with no problem. Which version do you use?

**Comment by fouziyapatel** [comment] 2017-05-17 10:04
I 'm using Xbim.Essentials-4.0.27 .
Thanks .

**Comment by fouziyapatel** [comment] 2017-05-17 10:23
I'm not getting Xbim.Essentials 4.0.28-V018  version from Nugget. Can you please share link.

**Comment by martin1cerny** [comment] 2017-05-18 07:18
See the *Compilation* section on [our website](http://docs.xbim.net) please. There are links to MyGet which once added to your NuGet Package Manager will give you access to our development builds. We are just about to publish development branch to master (and hence to NuGet.org as well). So if it is not critical you can just wait for a few days (max 2 weeks I think).

**Comment by CBenghi** [comment] 2017-05-19 11:00
@fouziyapatel, 
since you have probably edited the issue to remove the file, the issue is no longer adequately documented, so I'll close it.
Best,
Claudio

**Closed by CBenghi** 2017-05-19 11:00 UTC

**Comment by fouziyapatel** [comment] 2017-05-19 17:39
I'm so sorry.You are taking it wrong way .I have added MyGet link but failed to get updated version of Xbim.Essentials and waiting to get it on NuGet. I think i must try again adding myget link in visual studio 2015.
Thanks.
