### ISSUE TITLE
IfcStore can't open .ifcxml in .ifczip

### ISSUE THREAD

**Issue by nemarkovic** [xBimTeam/XbimEssentials#258] opened 2019-04-24 15:50 UTC
*Short summary describing the issue. (3-5 sentences)*
When I try to open a .ifczip that has a .ifcxml in it I get an NotSupportedException.
#### Assemblies and versions affected:

*Which assemblies/packages and their versions are known to be affected. E.g. __Xbim.Essentials 4.0.29__*

#### Steps (or code) to reproduce the issue:
1. zip a .ifcxml
2. try to open it

IModel model = IfcStore.Open(ifcFilename, null, -1, progressDelegate, XbimDBAccess.Read);

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*
[Samples.zip](https://github.com/xBimTeam/XbimEssentials/files/3113080/Samples.zip)

#### Expected behavior:
Opening the .ifcxml within the .ifczip file

*What would you expect to happen*

#### Actual behavior or exception details:.
System.Exception: 'Error reading XML, Line=19, Position=251, Tag='''
Inner Exception: NotSupportedException: This operation is not supported.
https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.IO.MemoryModel/Xml/XbimXmlReader3.cs
It breaks at line 896 then it continues to fall through.
*What actually is happening*

#### Additional Details

*Optional, details of the root cause if known. 
Delete this section if you have no additional details to add.*

**Comment by andyward** [comment] 2019-04-26 08:11
Have you tried this with the latest v5 Xbim.Essentials? There was a lot of refactoring around the IfcStore in the last release.

**Comment by nemarkovic** [comment] 2019-05-06 07:44
I'm currently using v5 (5.0.225)

**Comment by andyward** [comment] 2019-05-09 16:24
This should be fixed in develop. I've pushed through to XBimXplorer so you can test.

Took a while to reproduce the issue: it only occurs when using a Progress delegate is provided on file open for zipped IfcXml streams. Root cause is that the DeflateStream is not seekable, so progress reporting was failing.

**Closed by andyward** 2019-05-09 16:24 UTC
Labels: bug
