### ISSUE TITLE
Failed to add entity to the database

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimEssentials#18] opened 2016-02-25 14:12 UTC
During the research the xBIM Toolkit I found the problem.
Unfortunately, InsertCopy method throws an exception:
Message = "Failed to add entity to the database"
InnerException = {"Illegal duplicate key"}

The test was taken from the file:
https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Essentials.Tests/ModelFilterTest.cs

As well as, I write test:

       [TestMethod]
        public void CopyFileToFileTest()
        {
            using (var source = new XbimModel())
            {

                PropertyTranformDelegate propTransform = delegate (IfcMetaProperty prop, object toCopy)
                {
                    var value = prop.PropertyInfo.GetValue(toCopy, null);
                    return value;
                };
                string ifcFilename_1 = @"c:\\Temp\\House_1.ifc",
                    ifcFilename_2 = @"c:\\Temp\\House_2.ifc";               
                source.CreateFrom(ifcFilename_1, Path.GetTempFileName(), null, true);
                source.CacheStop();
                using (var target = new XbimModel())
                {
                    target.CreateFrom(ifcFilename_2, Path.GetTempFileName(), null, true);
                    target.CacheStop();
                    target.AutoAddOwnerHistory = false;
                    using (var txn = target.BeginTransaction())
                    {
                        var copied = new XbimInstanceHandleMap(source, target);
                        foreach (var item in source.Instances)
                        {
                            target.InsertCopy(item, copied, txn, propTransform);
                        }
                        txn.Commit();
                    }
                    target.SaveAs(ifcFilename_2);
                }
                source.Close();
                //the two files should be the same
            }
        }
`

In file XbimEntityCursor.cs, method **AddEntity** throws  an exception line 382.
`internal void AddEntity(int currentLabel, short typeId, IEnumerable<int> indexKeys, byte[] data, bool? indexed, XbimLazyDBTransaction? trans = null)`

**Comment by SteveLockley** [comment] 2016-02-25 15:01
Dear kozintsev
we spotted this one too, it was caused by the preservation of entity labels and the way owner history had been implemented in XbimModel
The fixes are in the development branch. This branch for essentials and geometry is near release to master. This brings Ifc4 to xBIM and a lot of other features, however, you will have to make minor code changes to adopt this version, mostly this involves the use of the schema neutral IfcStore rather than XbimModel. We will shortly put out some guidance on upgrading if you want to wait. Alternatively if you look at the code in master and ensure that insert copy is creating new entity labels for each insertion I think this will work around

**Comment by kozintsev** [comment] 2016-02-29 13:58
Hello Steve!
I tested the developer version and found exactly the same exception.
For example my test:

`

       [TestMethod]
        public void MergeEntitiesTest()
        {
            var sourceFile = @"c:\Temp\HelloWall.ifc";// @"d:\ArciCAD\test_v2.ifc";
            var copyFile = @"c:\Temp\copy.ifc";
            var targetFile = @"c:\Temp\House.ifc";//@"d:\ArciCAD\test_v2_ins.ifc";
            using (var source = new Xbim.Ifc2x3.IO.XbimModel())
            {
                PropertyTranformDelegate propTransform = delegate (ExpressMetaProperty prop, object toCopy)
                {
                    var value = prop.PropertyInfo.GetValue(toCopy, null);
                    return value;
                };
               
                source.CreateFrom(sourceFile, Path.GetTempFileName(), null,true);

                using (var target = new Xbim.Ifc2x3.IO.XbimModel())
                {
                    target.CreateFrom(targetFile, Path.GetTempFileName(), null, true);
                    target.AutoAddOwnerHistory = true;

                    var ps_source = source.Instances.OfType<IfcBuildingElement>();
                    var ps_target= target.Instances.OfType<IfcBuildingElement>();
                    bool rencontre = false;
                    using (var txn = target.BeginTransaction())
                    {
                        //target.Header = source.Header;
                        var copied = new XbimInstanceHandleMap(source, target);

                        foreach (var item_s in ps_source)
                        {
                            //var cpy =  target.InsertCopy(item, copied, txn, propTransform, true);
                            rencontre = false;
                            foreach (var item_t in ps_target)
                            {
                                if (item_s.GlobalId == item_t.GlobalId)
                                {
                                    rencontre = true;
                                    break; 
                                }
                            }
                            if (!rencontre)
                                target.InsertCopy(item_s, copied, propTransform, true, false);
                        }
                        txn.Commit();
                    }
                    target.SaveAs(copyFile);
                }
                source.Close();
            }
        }
`

Exception in;
EsentEntityCursor.cs line 391

{"Failed to add entity to the database"}
{"Illegal duplicate key"}

**Comment by SteveLockley** [comment] 2016-03-02 08:02
try this and see if the problem goes away
target.InsertCopy(item_s, copied, propTransform, false, false);
if it does the problem is with the creation of duplication IfcOwnerHistoryObjects, fixed in the develop  branch

**Comment by martin1cerny** [comment] 2016-03-15 14:14
Dear @kozintsev ,
please note that XbimModel is deprecated in the new Essentials. You should use IfcStore class instead.
If you are going to use the model as a target for `InsertCopy()` function with `keepLabels = true` please make sure to create it **without** editor credentials. It causes new objects to be created in the database (IfcOwnerHistory + related) and their entity labels may potentially clash with the labels of objects you are inserting. It is the same case as when you insert entities from multiple models into one.

**Closed** 2016-03-15 14:14 UTC
