### ISSUE TITLE
Building a VS 2019 Install Project with xBim resulting in many errors and warnings. 

### ISSUE THREAD

**Issue by Aniobodo** [xBimTeam/XbimEssentials#275] opened 2019-07-24 08:04 UTC
It seems that nugget package references are different. 

Two or more objects have the same target location ('[targetdir]\system.runtime.serialization.primitives.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.runtime.serialization.primitives.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.runtime.serialization.primitives.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.runtime.serialization.primitives.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.net.http.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.net.http.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.net.http.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.net.http.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.diagnostics.tracing.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.diagnostics.tracing.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.diagnostics.tracing.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.diagnostics.tracing.dll')
WARNING: Two or more objects have the same target location ('[targetdir]\system.io.compression.dll')

**Comment by martin1cerny** [comment] 2019-07-24 12:28
This is unlikely caused by xBIM. You should first check the project itself without xBIM.

**Comment by Aniobodo** [comment] 2019-07-25 09:15
Hello martin1cerny,
I had to recheck again with xBim and without xBim. All I can see now points to xBim. I updated all xBim packages from nugget. The problems and errors occurs when building Setup project. The project is on .Net 4.7. Please see below:

------ Starting pre-build validation for project 'Setup2' ------ 
WARNING: Unable to find dependency 'SYSTEM.IO.COMPRESSION.FILESYSTEM' (Signature='B77A5C561934E089' Version='0.0.0.0') of assembly 'netstandard.dll'
WARNING: Unable to find dependency 'SYSTEM.IO.COMPRESSION.FILESYSTEM' (Signature='B77A5C561934E089' Version='0.0.0.0') of assembly 'netstandard.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'System.Memory.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'System.Memory.dll'
WARNING: Unable to find dependency 'SYSTEM.NUMERICS.VECTORS' (Signature='B03F5F7F11D50A3A' Version='4.1.3.0') of assembly 'System.Memory.dll'
WARNING: Unable to find dependency 'SYSTEM.NUMERICS.VECTORS' (Signature='B03F5F7F11D50A3A' Version='4.1.3.0') of assembly 'System.Memory.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'Microsoft.Extensions.Primitives.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='4.0.4.1') of assembly 'Microsoft.Extensions.Primitives.dll'
------ Pre-build validation for project 'Setup2' completed ------

**Comment by martin1cerny** [comment] 2019-07-25 14:10
I'm sorry but xBIM team doesn't have necessary experience with VS Install projects. But it seems to me you need to make sure your install project lists all the dependencies. These should mostly be part of the framework so I wonder if you mix new and old csproj formats in your solution. That causes dependencies to go little bit wild sometimes.

**Comment by andyward** [comment] 2019-07-25 16:29
Have you tried building a completely empty .netstandard2 project and testing your installer with that? Help try to rule out whether it's a Installer<->.netstandard issue, or installer<->xbim issue.

The 0.0.0.0 version numbers are where I'd be investigating. Doesn't sound right...

**Comment by andyward** [comment] 2019-12-30 12:03
Closing. Not an xbim issue

**Closed by andyward** 2019-12-30 12:03 UTC
