### ISSUE TITLE
Can't delete *.xBim file if the ifc File is invlalid

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimEssentials#8] opened 2015-07-29 13:33 UTC
Hello, I'm not sure if this is the right place.

When I open an invlaid ifc File an get an exception (there was an error in the string encoding, but I have the same thing with an invalid line, e.g. "#103= IFCBUILDING('1CP$KLp6fE0OAJmy4q$x53',#41,);
"), I can't delete the created *.xBim file as long my application is running.

xBimModel.CreateFrom(filePath, xBimFileName, LoadXbimProgress) 

I use xBimModel in a using directive.
When I had a closer look, there where still a thread of or with the StepP21Parser running, so
I could not delete the file

**Comment by andyward** [comment] 2015-08-03 14:01
I've been looking at this and can reproduce (although it's perhaps intermittent). It seems there may be some secondary exceptions occurring down in the Esent/JET layer while the parser is tidying up after IfcImport fails. I've a feeling this may be because we're accessing JET session across threads - which we should not be. 

I'll look into it a bit more.

**Comment by CBenghi** [comment] 2016-10-24 19:40
Hi All, 
I'm closing because we don't know if this bug still applies to version 4.x.
Happy to reopen if we can add a test case to the solution.
Thanks,
Claudio

**Closed by CBenghi** 2016-10-24 19:40 UTC
Labels: bug
